name: spine_dragon
description: A simple StageXL web app.
version: 0.0.1
#homepage: https://www.example.com
#author: xavier.hainaux <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  stagexl: ^1.1.0
  stagexl_spine: 0.9.0+2
 # stagexl_spine: 0.8.1

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives"]
    minify: true